from os import getenv

SECRET_KEY = getenv("SECRET_KEY")
ALGORITHM = getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_DAYS = 3

ADMIN_EMAIL = getenv("EMAIL_ADMIN")
ADMIN_PASSWORD = getenv("HASHED_ADMIN_PASSWORD")
